network=main
genesis_block=118862949
genesis_hash=9fe3e16aa0ed0ebff6a603df356fc707fb6d9ee96d8790dc08ba95a8cc7bda25
default_peer=http://safire.org:4888
strict_genesis=1

creator_mode=1

storage_profile=desktop
